import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";
import { PDFDocument, StandardFonts, rgb } from "https://esm.sh/pdf-lib@1.17.1";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });

type GenerateReceiptRequest = {
  dueId?: string;
};

type ResidentDueRow = {
  id: string;
  amount: number;
  status: string;
  paid_at: string | null;
  payment_reference: string | null;
  estate_id: string | null;
  receipt_url: string | null;
  due: { title: string | null } | null;
  resident: {
    house_unit_number: string | null;
    user_id: string;
  } | null;
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  if (req.method !== "POST") return json({ ok: false, error: "Method not allowed" }, 405);

  try {
    const { dueId } = (await req.json()) as GenerateReceiptRequest;
    if (!dueId) return json({ ok: false, error: "dueId is required" }, 400);

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
      { auth: { autoRefreshToken: false, persistSession: false } },
    );

    const { data: residentDue, error: fetchError } = await supabase
      .from("resident_dues")
      .select(`
        id, amount, status, paid_at, payment_reference, estate_id, receipt_url,
        due:dues(title),
        resident:residents(house_unit_number, user_id)
      `)
      .eq("id", dueId)
      .maybeSingle();

    if (fetchError) throw fetchError;
    if (!residentDue) return json({ ok: false, error: "Payment record not found" }, 404);
    const due = residentDue as unknown as ResidentDueRow;

    let residentName = "Resident";
    if (due.resident?.user_id) {
      const { data: profile } = await supabase
        .from("profiles")
        .select("full_name")
        .eq("id", due.resident.user_id)
        .maybeSingle();
      if (profile?.full_name) residentName = profile.full_name;
    }

    let brandName = "XTATE";
    if (due.estate_id) {
      const { data: tenant } = await supabase
        .from("tenants")
        .select("name")
        .eq("estate_id", due.estate_id)
        .maybeSingle();
      if (tenant?.name) brandName = tenant.name;
    }

    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([420, 560]);
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    let y = 500;
    const drawLine = (text: string, options: { bold?: boolean; size?: number; color?: [number, number, number] } = {}) => {
      page.drawText(text, {
        x: 40,
        y,
        size: options.size ?? 12,
        font: options.bold ? boldFont : font,
        color: options.color ? rgb(...options.color) : rgb(0.1, 0.1, 0.1),
      });
      y -= (options.size ?? 12) + 10;
    };

    drawLine(brandName, { bold: true, size: 22, color: [0.11, 0.31, 0.85] });
    drawLine("Payment Receipt", { bold: true, size: 14 });
    y -= 10;
    drawLine(`Resident: ${residentName}`);
    drawLine(`Unit: ${due.resident?.house_unit_number || "-"}`);
    drawLine(`Due: ${due.due?.title || "Estate due"}`);
    drawLine(`Amount: NGN ${Number(due.amount).toLocaleString()}`);
    drawLine(`Status: ${due.status}`);
    drawLine(`Reference: ${due.payment_reference || "-"}`);
    drawLine(`Paid At: ${due.paid_at ? new Date(due.paid_at).toLocaleString() : "-"}`);
    y -= 20;
    drawLine("Generated by XTATE Estate OS", { size: 9, color: [0.5, 0.5, 0.5] });

    const pdfBytes = await pdfDoc.save();
    const filePath = `${due.estate_id || "unassigned"}/${due.id}.pdf`;

    const { error: uploadError } = await supabase.storage
      .from("receipts")
      .upload(filePath, pdfBytes, { contentType: "application/pdf", upsert: true });

    if (uploadError) throw uploadError;

    const { error: updateError } = await supabase
      .from("resident_dues")
      .update({ receipt_url: filePath })
      .eq("id", due.id);

    if (updateError) throw updateError;

    const { data: signedUrlData, error: signedUrlError } = await supabase.storage
      .from("receipts")
      .createSignedUrl(filePath, 60 * 5);

    if (signedUrlError) throw signedUrlError;

    return json({ ok: true, filePath, signedUrl: signedUrlData.signedUrl });
  } catch (error) {
    console.error("generate-payment-receipt error", error);
    return json({ ok: false, error: error instanceof Error ? error.message : "Failed to generate receipt" }, 500);
  }
});
